# Global parameters
[global]
	dns forwarder = 8.8.8.8
	netbios name = FILESERVER
	realm = TECTON.LOCAL
	server role = active directory domain controller
	workgroup = TECTON
	idmap_ldb:use rfc2307 = yes
	printing = cups
        printcap name = cups
        load printers = yes
	rpc_server:spoolss = embedded
        rpc_daemon:spoolssd = embedded

[sysvol]
	path = /var/lib/samba/sysvol
	read only = No

[netlogon]
	path = /var/lib/samba/sysvol/tecton.local/scripts
	read only = No
[Kozos]
path = /srv/samba/megosztasok/Kozos
read only = no
guest ok = no

[Penzugy]
path = /srv/samba/megosztasok/Penzugy
read only = no

[Strategiai]
path = /srv/samba/megosztasok/Strategiai
read only = no

[printers]
   comment = All Printers
   path = /var/spool/samba
   browseable = yes
   guest ok = no
   writable = no
   printable = yes

[PDF]
   comment = Tecton Virtual PDF Printer
   path = /var/spool/samba
   printable = yes
   lpq command = /usr/bin/lpstat -o PDF
   lprm command = /usr/bin/cancel %p-%j
   print command = /usr/bin/lpr -P PDF %s; rm %s
   browseable = yes
   guest ok = yes

[print$]
   comment = Printer Drivers
   path = /var/lib/samba/printers
   browseable = yes
   read only = yes
   guest ok = no
